require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRailsVersion: 7
