require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'

Naming/VariableNumber:
  EnforcedStyle: 'snake_case'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRailsVersion: 7
