version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=sdeks
      - POSTGRES_PASSWORD=sdeks
    ports:
      - "5433:5432"

  redis:
    image: redis
    command: redis-server --appendonly yes

  sdeks:
    image: sdeks:local
    build:
      context: .
      args:
        RAILS_ENV: development
    volumes:
      - ./:/rails_app
      - gem_cache:/usr/local/bundle
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgresql://sdeks:sdeks@pg
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_MAX_THREADS=2
      - REVISION=c079966-fake-revision
    links:
      - redis:redis
      - postgres:pg

volumes:
  gem_cache: