version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=kade
      - POSTGRES_PASSWORD=kade
    ports:
      - "5433:5432"

  redis:
    image: redis
    command: redis-server --appendonly yes

  api:
    image: kade:local
    build:
      context: .
      args:
        RAILS_ENV: development
    volumes:
      - ./:/rails_app
      - gem_cache:/usr/local/bundle
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgresql://kade:kade@pg
      - REDIS_URL=redis://redis:6379/0
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_MAX_THREADS=2
      - REVISION=c079966-fake-revision
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}
    links:
      - redis:redis
      - postgres:pg

  sidekiq:
    image: kade:local
    volumes:
      - ./:/rails_app
      - gem_cache:/usr/local/bundle
    command: ["bundle", "exec", "sidekiq"]
    environment:
      - SIDEKIQ_VERBOSE=true
      - DATABASE_URL=postgresql://kade:kade@pg
      - REDIS_URL=redis://redis:6379/0
      - RAILS_MAX_THREADS=1
      - RAILS_LOG_TO_STDOUT=true
      - AZURE_STORAGE_ACCOUNT_NAME=${AZURE_STORAGE_ACCOUNT_NAME}
      - AZURE_STORAGE_ACCESS_KEY=${AZURE_STORAGE_ACCESS_KEY}
    links:
      - redis:redis
      - postgres:pg

volumes:
  gem_cache: