test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/#{Rails.env}") %>

development:
  service: Disk
  root: <%= Rails.root.join("tmp/storage/#{Rails.env}") %>

staging:
  service: AzureStorage
  storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['AZURE_STORAGE_ACCESS_KEY'] %>
  container: 'staging'

production:
  service: AzureStorage
  storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['AZURE_STORAGE_ACCESS_KEY'] %>
  container: 'production'
