name: Zooni CI
on:
  pull_request:
  push: { branches: main }
env:
  DATABASE_URL: postgresql://sdeks:sdeks@localhost/gh_ci_test
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: sdeks
          POSTGRES_PASSWORD: sdeks
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Check for focus specs
        run: |
          ! grep -R --exclude=spec_helper.rb "\(describe\|context\|it\).*\(:focus\|focus:\)" spec/
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Install PG Client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Setup DB and configs
        run: |
          RAILS_ENV=test bundle exec rake db:setup
      - name: Run tests
        run: RAILS_ENV=test bundle exec rspec
